### ISSUE TITLE
useless plugins in the vegetable-lambda example?

### ISSUE THREAD

**Issue by xpepper** [DaikonWeb/daikon-examples#4]
Are `maven` and `java` plugins really required for the example?

![daikon-examples:build gradle at master · DaikonWeb:daikon-examples 2020-03-30 15-09-44](https://user-images.githubusercontent.com/450934/77916064-c8579580-7298-11ea-9c24-c4ec1ba1daaa.png)

**Comment by AlessioCoser** [comment]
I think there is no need to use those plugins

**Comment by AlessioCoser** [comment]
Thank you! Just removed!
